name: autotests demo-shop

on:
  workflow_dispatch:

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout autotest
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install playwright
        run: playwright install
      - name: run tests
        run: pytest
      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: UploaAd Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 30

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Install Allure
        run: |
          curl -sL https://allurereport.org/downloads/2.27.0/allure_2.27.0-1_all.deb -o allure.deb
          sudo dpkg -i allure.deb || true
          sudo apt-get install -f -y
          allure --version

      - name: Generate Allure Report
        if: always()
        run: |
          if [ -d "gh-pages" ]; then
            cp -r gh-pages/history allure-results/ || true
          fi
          allure generate allure-results -o allure-report --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
          keep_files: false


############
#      - name: Checkout repo
#        uses: actions/checkout@v4
#
##      - name: Get Allure history
##        uses: actions/checkout@v4
##        continue-on-error: true
##        with:
##          ref: gh-pages
##          path: gh-pages
##
##      - name: Allure Report action from repo
##        uses: ./
##        with:
##          allure_results: allure-results
##          allure_history: allure-history
##          keep_reports: 20
##
##      - name: Deploy report to Github Pages
##        uses: peaceiris/actions-gh-pages@v4
##        with:
##          github_token: ${{ secrets.GITHUB_TOKEN }}
##          publish_branch: gh-pages
##          publish_dir: allure-history