name: autotests demo-shop

on:
  workflow_dispatch:

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout autotest
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install playwright
        run: playwright install
      - name: run tests
        run: pytest
      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Load Allure report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: always()
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-history
          force_orphan: true
          user_name: 'github-actions'
          user_email: 'github-actions@github.com'
